/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DBLayer.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class ManagePartSupplier extends javax.swing.JFrame {

    Color mouseEnterColor = new Color(255, 0, 0);
    Color mouseExitColor = new Color(204, 0, 0);

    public ManagePartSupplier() {
        initComponents();
        Updatetable();
    }

    public void ClearButton() {

        txtSupCodeNo.setText("");
        txtSupCompany.setText("");
        txtCompanyConNumber.setText("");
        txtCompEmailAdd.setText("");
        txtTotal.setText("");
        txtAmntToPaid.setText("");
        txtAmntDue.setText("");
        txtItemCode.setText("");
        txtItemName.setText("");
        txtItemQuantity.setText("");
        txtItemSerialNum.setText("");
        rdoNew.setSelected(false);
        rdoUsed.setSelected(false);

    }

    DefaultTableModel model;

    private void Updatetable() {

        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            String sql = "select * from managepartsupp";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String iid = rs.getString("SComCode");
                String name = rs.getString("SComName");
                String contact = rs.getString("ComContact");
                String email = rs.getString("ComEmailAdd");
                String total = rs.getString("total");
                String topaid = rs.getString("AmountToPaid");
                String due = rs.getString("AmountDue");
                String code = rs.getString("ItemCode");
                String iname = rs.getString("ItemName");
                String iquantity = rs.getString("ItemQuant");
                String serial = rs.getString("ItemSerial");

                Object[] obj = {iid, name, contact, email, total, topaid, due, code, iname, iquantity, serial};
                model = (DefaultTableModel) Table.getModel();
                model.addRow(obj);
            }

        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, e);

        }
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnEnter = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtClear = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel14 = new javax.swing.JLabel();
        txtSupCompany = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSupCodeNo = new javax.swing.JTextField();
        txtCompanyConNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCompEmailAdd = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtItemQuantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtItemSerialNum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rdoNew = new javax.swing.JRadioButton();
        rdoUsed = new javax.swing.JRadioButton();
        txtItemCode = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAmntToPaid = new javax.swing.JTextField();
        txtAmntDue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCalDue = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEnter.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\add-icon.png")); // NOI18N
        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 170, 50));

        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\edit-icon.png")); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 170, 50));

        txtClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtClear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\Actions-edit-clear-icon.png")); // NOI18N
        txtClear.setText("Clear Fields");
        txtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClearActionPerformed(evt);
            }
        });
        jPanel1.add(txtClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 170, 50));

        btnRemove.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\Misc-Delete-Database-icon.png")); // NOI18N
        btnRemove.setText("Remove entries");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 170, 50));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier No", "Supplier Company", "Company Contact", "Company Email", "TotalCost", "Amount to paid", "amount due", "Item Code", "Item Name", "Item Quantity", "Item serial", "Item Condition"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 1100, 230));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 255, 1, 58));

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setToolTipText("");
        jLayeredPane1.setName("Supplier Details"); // NOI18N
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Supplier Details");
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 9, -1, -1));

        txtSupCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupCompanyActionPerformed(evt);
            }
        });
        jLayeredPane1.add(txtSupCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 55, 190, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Supplier Company");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 61, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Supplier Code No");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        txtSupCodeNo.setEditable(false);
        txtSupCodeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupCodeNoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(txtSupCodeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 108, 190, -1));
        jLayeredPane1.add(txtCompanyConNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 167, 190, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Contact Number ");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 173, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Email Address");
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 230, -1, -1));
        jLayeredPane1.add(txtCompEmailAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 224, 190, -1));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 360, 300));

        jLayeredPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Item Details");
        jLayeredPane2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 9, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Item Code");
        jLayeredPane2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 116, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Item Name");
        jLayeredPane2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 62, -1, -1));
        jLayeredPane2.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 56, 190, -1));
        jLayeredPane2.add(txtItemQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 165, 190, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Quantity");
        jLayeredPane2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 171, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Serial number");
        jLayeredPane2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 219, -1, -1));
        jLayeredPane2.add(txtItemSerialNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 213, 190, -1));

        jLabel11.setText("Item Condition");
        jLayeredPane2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 264, -1, -1));

        buttonGroup1.add(rdoNew);
        rdoNew.setText("New");
        rdoNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNewActionPerformed(evt);
            }
        });
        jLayeredPane2.add(rdoNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 263, -1, -1));

        buttonGroup1.add(rdoUsed);
        rdoUsed.setText("Used");
        rdoUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoUsedActionPerformed(evt);
            }
        });
        jLayeredPane2.add(rdoUsed, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 263, -1, -1));

        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });
        jLayeredPane2.add(txtItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, -1));

        jPanel1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 360, 300));

        jLayeredPane3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Payments");
        jLayeredPane3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 9, -1, -1));
        jLayeredPane3.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 56, 144, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Total Cost");
        jLayeredPane3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 62, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Amount to be Paid");
        jLayeredPane3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 106, -1, 27));
        jLayeredPane3.add(txtAmntToPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 105, 144, -1));
        jLayeredPane3.add(txtAmntDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 157, 144, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Amount Due");
        jLayeredPane3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 156, -1, 31));

        btnCalDue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCalDue.setText("Calculate Due");
        btnCalDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalDueActionPerformed(evt);
            }
        });
        jLayeredPane3.add(btnCalDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 234, 139, -1));

        jPanel1.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 360, 300));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\icons8_Rewind_48px.png")); // NOI18N
        jLabel17.setText("Back");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("x");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 420, 5));

        jLabel18.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Manage Part Suppliers");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 530, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        int row = Table.getSelectedRow();
        TableModel model = Table.getModel();
        txtSupCodeNo.setText(model.getValueAt(row, 1).toString());
        txtSupCompany.setText(model.getValueAt(row, 0).toString());
        txtCompanyConNumber.setText(model.getValueAt(row, 2).toString());
        txtCompEmailAdd.setText(model.getValueAt(row, 3).toString());
        txtTotal.setText(model.getValueAt(row, 4).toString());
        txtAmntToPaid.setText(model.getValueAt(row, 5).toString());
        txtAmntDue.setText(model.getValueAt(row, 6).toString());
        txtItemCode.setText(model.getValueAt(row, 7).toString());
        txtItemName.setText(model.getValueAt(row, 8).toString());
        txtItemQuantity.setText(model.getValueAt(row, 9).toString());
        txtItemSerialNum.setText(model.getValueAt(row, 10).toString());
        String itemCondition = (model.getValueAt(row, 11).toString());
        if ("New".equals(itemCondition)) {
            rdoNew.setSelected(true);
        }
        if ("Used".equals(itemCondition)) {
            rdoUsed.setSelected(true);

        }

        String click = (Table.getModel().getValueAt(row, 0).toString());

        try {
            DBConnection con = new DBConnection();
            String sql = "select* from managepartsupp where SComCode=' " + click + " '  ";
            PreparedStatement prep = con.prepareStatement(sql);
            ResultSet r = prep.executeQuery();

            if (r.next()) {
                String SComCode = r.getString("SComCode");
                txtSupCodeNo.setText(model.getValueAt(row, 0).toString());

                String SComName = r.getString("SComName");
                txtSupCompany.setText(SComName);

                String ComContact = r.getString("ComContact");
                txtCompanyConNumber.setText(ComContact);

                String ComEmailAdd = r.getString("ComEmailAdd");
                txtCompEmailAdd.setText(ComEmailAdd);

                String total = r.getString("total");
                txtTotal.setText(total);

                String AmountToPaid = r.getString("AmountToPaid");
                txtAmntToPaid.setText(AmountToPaid);

                String AmountDue = r.getString("AmountDue");
                txtAmntDue.setText(AmountDue);

                String ItemCode = r.getString("ItemCode");
                txtItemCode.setText(ItemCode);

                String ItemName = r.getString("ItemName");
                txtItemName.setText(ItemName);

                String ItemQuant = r.getString("ItemQuant");
                txtItemQuantity.setText(ItemQuant);

                String ItemSerial = r.getString("ItemSerial");
                txtItemSerialNum.setText(ItemSerial);

                //================================================
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_TableMouseClicked

    private void rdoUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoUsedActionPerformed
        // TODO add your handling code here:
        itemCondition = "Used";
    }//GEN-LAST:event_rdoUsedActionPerformed

    private void rdoNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNewActionPerformed
        // TODO add your handling code here:
        itemCondition = "New";
    }//GEN-LAST:event_rdoNewActionPerformed

    private void txtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClearActionPerformed
        // TODO add your handling code here:
        ClearButton();
    }//GEN-LAST:event_txtClearActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {

            DBConnection con = new DBConnection();
            String sql = "UPDATE managepartsupp set SComName=? , ComContact=? , ComEmailAdd=? , total=? , AmountToPaid=? , AmountDue=? ,  ItemCode=? , ItemName=? , ItemQuant=? , ItemSerial=? , ItemCondition=? WHERE SComCode=?";

            PreparedStatement prep = con.prepareStatement(sql);

            prep.setString(1, txtSupCompany.getText());
            prep.setString(2, txtCompanyConNumber.getText());
            prep.setString(3, txtCompEmailAdd.getText());
            prep.setInt(4, Integer.parseInt(txtTotal.getText().trim()));
            prep.setInt(5, Integer.parseInt(txtAmntToPaid.getText().trim()));
            prep.setInt(6, Integer.parseInt(txtAmntDue.getText().trim()));
            prep.setInt(7, Integer.parseInt(txtItemCode.getText().trim()));
            prep.setString(8, txtItemName.getText());
            prep.setInt(9, Integer.parseInt(txtItemQuantity.getText().trim()));
            prep.setString(10, txtItemSerialNum.getText());
            prep.setString(11, itemCondition);
            prep.setString(12, txtSupCodeNo.getText());

            prep.execute();
            JOptionPane.showMessageDialog(this, "Edit Saved");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

        clearTable();
        Updatetable();
        ClearButton();

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:

        try {
            DBConnection con = new DBConnection();
            String sql = "INSERT INTO managepartsupp(SComName,ComContact,ComEmailAdd,total,AmountToPaid,AmountDue,ItemCode,ItemName,ItemQuant,ItemSerial,ItemCondition)" + "values(?,?,?,?,?,?,?,?,?,?,?)";
            String sql1 = "insert into expense(expenses, date) values(?,curdate());";
            PreparedStatement pst = con.prepareStatement(sql);
            PreparedStatement pst1 = con.prepareStatement(sql1);

            pst.setString(1, txtSupCompany.getText().trim());
            pst.setString(2, txtCompanyConNumber.getText().trim());
            pst.setString(3, txtCompEmailAdd.getText().trim());

            pst.setInt(4, Integer.parseInt(txtTotal.getText().trim()));
            pst.setInt(5, Integer.parseInt(txtAmntToPaid.getText().trim()));
            pst.setInt(6, Integer.parseInt(txtAmntDue.getText().trim()));
            pst.setInt(7, Integer.parseInt(txtItemCode.getText().trim()));

            pst.setString(8, txtItemName.getText().trim());

            pst.setInt(9, Integer.parseInt(txtItemQuantity.getText().trim()));

            pst.setString(10, txtItemSerialNum.getText().trim());
            pst.setString(11, itemCondition);

            pst.execute();

            pst1.setDouble(1, Double.parseDouble(txtTotal.getText().trim()));
            pst1.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data Entered");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        clearTable();
        Updatetable();
        ClearButton();

    }//GEN-LAST:event_btnEnterActionPerformed

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void txtSupCodeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupCodeNoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSupCodeNoActionPerformed

    private void txtSupCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupCompanyActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:

        if (txtSupCodeNo.getText().equals("SComCode")) {
            JOptionPane.showMessageDialog(null, "Please Select The Data Which You Need To Delete");
        } else {
            int p = JOptionPane.showConfirmDialog(null, "Please Confirm To Delete", "Delete", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                try {
                    DBConnection con = new DBConnection();
                    String sql = "delete from managepartsupp where SComCode=?";
                    PreparedStatement prep = con.prepareStatement(sql);

                    prep.setString(1, txtSupCodeNo.getText());
                    prep.execute();

                    JOptionPane.showMessageDialog(null, " Deleted");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            clearTable();
            Updatetable();
            ClearButton();
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCalDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalDueActionPerformed
        // TODO add your handling code here:
        AmountToPaid = Integer.parseInt(txtAmntToPaid.getText().trim());
        Total = Integer.parseInt(txtTotal.getText());
        AmountDue = Total - AmountToPaid;
        txtAmntDue.setText(Integer.toString(AmountDue));

    }//GEN-LAST:event_btnCalDueActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        HomePageUI ui = new HomePageUI();
        ui.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        jPanel2.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        jPanel2.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePartSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePartSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePartSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePartSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePartSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnCalDue;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnRemove;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rdoNew;
    private javax.swing.JRadioButton rdoUsed;
    private javax.swing.JTextField txtAmntDue;
    private javax.swing.JTextField txtAmntToPaid;
    private javax.swing.JButton txtClear;
    private javax.swing.JTextField txtCompEmailAdd;
    private javax.swing.JTextField txtCompanyConNumber;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemQuantity;
    private javax.swing.JTextField txtItemSerialNum;
    private javax.swing.JTextField txtSupCodeNo;
    private javax.swing.JTextField txtSupCompany;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
    private String itemCondition;
    private int Total = 0;
    private int AmountDue = 0;
    private int AmountToPaid = 0;
}
