package Views;

import Code.InvoiceCode;
import DBLayer.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageWatchSales extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    Color mouseEnterColor = new Color(255, 0, 0);
    Color mouseExitColor = new Color(204, 0, 0);

    public ManageWatchSales() {
        initComponents();
        Update_table();
    }

    public void Clearfields() {

        txtID.setText("");
        txt_cusname.setText("");
        txtCusNIC.setText("");
        txtBrand.setText("");
        txtColor.setText("");
        txtSNum.setText("");
        txtbillFill.setText("");
        txtPrice.setText("");
        txtBalance.setText("");
        txtPaidAmount.setText("");
        rdoCash.setSelected(false);
        rdoCards.setSelected(false);
        rdoSmart.setSelected(false);
        rdoAnalog.setSelected(false);
        rdoDigital.setSelected(false);

    }

    DefaultTableModel model;

    private void Update_table() {

        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            String sql = "select * from invoice";
            //PreparedStatement prep = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);

            //tbl_maintable.setModel(DbUtils.resultSetToTableModel(rs));
            while (rs.next()) {
                String inid = rs.getString("invoiceID");
                String cusname = rs.getString("cusname");
                String cusid = rs.getString("cusNIC");
                String brand = rs.getString("Brand");
                String color = rs.getString("Color");
                String snum = rs.getString("SNum");
                String price = rs.getString("Price");
                String pamount = rs.getString("PaidAmount");
                String balance = rs.getString("Balance");
                String pmethod = rs.getString("PaymentMethod");
                String wtype = rs.getString("WatchType");

                Object[] obj = {inid, cusname, cusid, brand, color, snum, pmethod, wtype, price, pamount, balance};
                model = (DefaultTableModel) tbl_maintable.getModel();
                model.addRow(obj);
            }

        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, e);

        }

    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_maintable.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cusname = new javax.swing.JTextField();
        txtCusNIC = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtSNum = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_maintable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnprintbill = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbillFill = new javax.swing.JTextArea();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        rdoCash = new javax.swing.JRadioButton();
        rdoCards = new javax.swing.JRadioButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        rdoSmart = new javax.swing.JRadioButton();
        rdoAnalog = new javax.swing.JRadioButton();
        rdoDigital = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtPaidAmount = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setForeground(new java.awt.Color(153, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Manage Watch Sales Invoices");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 530, 50));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer NIC");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 101, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Brand ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 37, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Serial Number ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 90, -1));

        txt_cusname.setForeground(new java.awt.Color(0, 0, 0));
        txt_cusname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cusnameActionPerformed(evt);
            }
        });
        jPanel3.add(txt_cusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 244, -1));

        txtCusNIC.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtCusNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 244, -1));

        txtBrand.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 248, 30));

        txtColor.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 250, -1));

        txtSNum.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtSNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 250, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 10, 340));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 934, 10));

        tbl_maintable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "InvoiceID", "CustomerName ", "CustomerNIC", "Brand", "Color ", "SerialNumber ", "PaymentMethod ", "Watch Type ", "Price", "Paid Amount", "balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_maintable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_maintableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_maintable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 430, 920, 250));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\add-icon.png")); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 157, 60));

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\edit-icon.png")); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 720, 160, 60));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\Misc-Delete-Database-icon.png")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 720, 176, 59));

        btnprintbill.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnprintbill.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\invoice-icon.png")); // NOI18N
        btnprintbill.setText("PRINT BILL");
        btnprintbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintbillActionPerformed(evt);
            }
        });
        jPanel3.add(btnprintbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 720, 312, 58));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\Actions-edit-clear-icon.png")); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 720, 185, 60));

        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 75, -1));

        txtbillFill.setColumns(20);
        txtbillFill.setRows(5);
        jScrollPane2.setViewportView(txtbillFill);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 400, 600));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payment Method");

        buttonGroup2.add(rdoCash);
        rdoCash.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rdoCash.setForeground(new java.awt.Color(255, 255, 255));
        rdoCash.setText("Cash");
        rdoCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCashActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoCards);
        rdoCards.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rdoCards.setForeground(new java.awt.Color(255, 255, 255));
        rdoCards.setText("Credit/Debit Card ");
        rdoCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCardsActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rdoCash, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rdoCards, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(rdoCash, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(rdoCards)
                .addGap(48, 48, 48))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCards)
                    .addComponent(rdoCash))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel3.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 390, -1));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(rdoSmart);
        rdoSmart.setForeground(new java.awt.Color(255, 255, 255));
        rdoSmart.setText("Smart ");
        rdoSmart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSmartActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoAnalog);
        rdoAnalog.setForeground(new java.awt.Color(255, 255, 255));
        rdoAnalog.setText("Analog");
        rdoAnalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAnalogActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoDigital);
        rdoDigital.setForeground(new java.awt.Color(255, 255, 255));
        rdoDigital.setText("Digital ");
        rdoDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDigitalActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Watch Type");

        jLayeredPane2.setLayer(rdoSmart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(rdoAnalog, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(rdoDigital, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rdoSmart, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(rdoAnalog, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSmart)
                    .addComponent(rdoAnalog)
                    .addComponent(rdoDigital))
                .addContainerGap())
        );

        jPanel3.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 78, 39));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("paid amount");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, 39));

        txtPrice.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 257, 39));

        txtPaidAmount.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtPaidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 257, 39));

        txtBalance.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 257, 39));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Balance");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 55, 540, 5));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Invoice no.");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 20));

        jButton1.setText("Calculate Balance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 377, 61));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\Downloads\\icons\\icons8_Rewind_48px.png")); // NOI18N
        jLabel13.setText("Back");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("x");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, 20, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1523, 872));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//==========================Function===============================================

    //=============================================================================

    private void txt_cusnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cusnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cusnameActionPerformed

    private void rdoCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCashActionPerformed
        // TODO add your handling code here:
        PaymentMethod = "Cash";


    }//GEN-LAST:event_rdoCashActionPerformed

    private void tbl_maintableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_maintableMouseClicked
        // TODO add your handling code here:

        int row = tbl_maintable.getSelectedRow();
        String Table_click = (tbl_maintable.getModel().getValueAt(row, 0).toString());

        try {
            Connection con = DBConnection.getConnection();
            String sql = "select * from invoice where invoiceID=' " + Table_click + " '  ";
            PreparedStatement prep = con.prepareStatement(sql);
            ResultSet rs = prep.executeQuery();

            if (rs.next()) {
                String invoiceID = rs.getString("invoiceID");
                txtID.setText(invoiceID);

                String cusname = rs.getString("cusname");
                txt_cusname.setText(cusname);

                String cusNIC = rs.getString("cusNIC");
                txtCusNIC.setText(cusNIC);

                String Brand = rs.getString("Brand");
                txtBrand.setText(Brand);

                String Color = rs.getString("Color");
                txtColor.setText(Color);

                String SNum = rs.getString("SNum");
                txtSNum.setText(SNum);

                String Price = rs.getString("Price");
                txtPrice.setText(Price);

                String Paid = rs.getString("PaidAmount");
                txtPaidAmount.setText(Paid);

                String Balance = rs.getString("Balance");
                txtBalance.setText(Balance);

                //================================================
                String PaymentMethod = rs.getString("PaymentMethod");
                if ("Cash".equals(PaymentMethod)) {
                    rdoCash.setSelected(true);
                }
                if ("Card".equals(PaymentMethod)) {
                    rdoCards.setSelected(true);

                }

                //===========================================
                String WatchType = rs.getString("WatchType");
                if ("Smart".equals(WatchType)) {
                    rdoSmart.setSelected(true);
                }

                //===========================================
                if ("Analog".equals(WatchType)) {
                    rdoAnalog.setSelected(true);
                }

                //===========================================
                if ("Digital".equals(WatchType)) {
                    rdoDigital.setSelected(true);
                }
                //===========================================
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_tbl_maintableMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        try {
            Connection con = DBConnection.getConnection();
            String sql = "INSERT INTO invoice(cusname,cusNIC,Brand,Color,SNum,Price,PaidAmount,Balance,PaymentMethod,WatchType)" + "values(?,?,?,?,?,?,?,?,?,?)";
            String sql1 = "insert into income(income, date) values(?,curdate());";
            PreparedStatement prep = con.prepareStatement(sql);
            PreparedStatement pst1 = con.prepareStatement(sql1);

            prep.setString(1, txt_cusname.getText().trim());
            prep.setString(2, txtCusNIC.getText().trim());
            prep.setString(3, txtBrand.getText().trim());
            prep.setString(4, txtColor.getText().trim());
            prep.setString(5, txtSNum.getText().trim());
            prep.setDouble(6, Double.parseDouble(txtPrice.getText()));
            prep.setDouble(7, Double.parseDouble(txtPaidAmount.getText()));
            prep.setDouble(8, Double.parseDouble(txtBalance.getText()));
            prep.setString(9, PaymentMethod);
            prep.setString(10, WatchType);

            prep.execute();

            pst1.setDouble(1, Double.parseDouble(txtPrice.getText().trim()));
            pst1.executeUpdate();

            clearTable();
            Update_table();
            JOptionPane.showMessageDialog(this, "Successfully added to the database");
        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null,e);
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        if (txtID.getText().equals("invoiceID")) {
            JOptionPane.showMessageDialog(null, "Please Select The Data Which You Need To Delete");
        } else {
            int p = JOptionPane.showConfirmDialog(null, "Please Confirm To Delete", "Delete", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                try {
                    Connection con = DBConnection.getConnection();
                    String sql = "delete from invoice where invoiceID=?";
                    PreparedStatement prep = con.prepareStatement(sql);

                    prep.setString(1, txtID.getText());
                    prep.execute();

                    JOptionPane.showMessageDialog(null, "Successfully Deleted");

                } catch (Exception e) {
                    e.printStackTrace();
                    //JOptionPane.showMessageDialog(null, e);
                }
            }

            clearTable();
            Update_table();
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Clearfields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void rdoCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCardsActionPerformed
        // TODO add your handling code here:
        PaymentMethod = "Card";
    }//GEN-LAST:event_rdoCardsActionPerformed

    private void rdoSmartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSmartActionPerformed
        // TODO add your handling code here:
        WatchType = "Smart";
    }//GEN-LAST:event_rdoSmartActionPerformed

    private void rdoAnalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAnalogActionPerformed
        // TODO add your handling code here:
        WatchType = "Analog";
    }//GEN-LAST:event_rdoAnalogActionPerformed

    private void rdoDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDigitalActionPerformed
        // TODO add your handling code here:
        WatchType = "Digital";
    }//GEN-LAST:event_rdoDigitalActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:

        try {

            Connection con = DBConnection.getConnection();
            String sql = "UPDATE invoice set cusname=?,cusNIC=?,Brand=?,Color=?,SNum=?,Price=?,PaidAmount=?,Balance=?,PaymentMethod=?,WatchType=? WHERE invoiceID=? ";
            PreparedStatement prep = con.prepareStatement(sql);

            prep.setString(1, txt_cusname.getText());
            prep.setString(2, txtCusNIC.getText());
            prep.setString(3, txtBrand.getText());
            prep.setString(4, txtColor.getText());
            prep.setString(5, txtSNum.getText());
            prep.setDouble(6, Double.parseDouble(txtPrice.getText().trim()));
            prep.setDouble(7, Double.parseDouble(txtPaidAmount.getText().trim()));
            prep.setDouble(8, Double.parseDouble(txtBalance.getText().trim()));
            prep.setString(9, PaymentMethod);
            prep.setString(10, WatchType);
            prep.setString(11, txtID.getText());

            prep.execute();

            clearTable();
            Update_table();
            JOptionPane.showMessageDialog(this, "Successfully updated");

        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIDActionPerformed

    private void btnprintbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintbillActionPerformed
        // TODO add your handling code here:

        txtbillFill.append("\t***TIMETICKER INVOICE****\n\n\n"
                + "INVOICE No: " + txtID.getText() + "\n\n"
                + "\n======================================================\n"
                + "Customer name         :     " + txt_cusname.getText() + "\n\n"
                + "Customer NIC          :        " + txtCusNIC.getText() + "\n\n"
                + "BRAND          :                    " + txtBrand.getText() + "\n\n"
                + "COLOR         :                    " + txtColor.getText() + "\n\n"
                + "SERIAL NUMBER          :  " + txtSNum.getText() + "\n\n"
                + "PAYMENT METHOD       : " + PaymentMethod + "\n\n"
                + "WATCH TYPE            :       " + WatchType + "\n\n\n"
                + "-------------------------------------------------------\n"
                + "Price          :                          " + txtPrice.getText() + "\n\n"
                + "Paid Amount          :            " + txtPaidAmount.getText() + "\n\n"
                + "-------------------------------------------------------\n"
                + "Balance          :                    " + txtBalance.getText() + "\n\n"
                + "-------------------------------------------------------\n"
                + "                                            Thank You  !!! \n\n"
                + "                                             Come Again \n\n"
                + "\n======================================================"
        );

    }//GEN-LAST:event_btnprintbillActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PaidAmount = Double.parseDouble(txtPaidAmount.getText().trim());
        Price = Double.parseDouble(txtPrice.getText());
        balance = PaidAmount - Price;
        txtBalance.setText(Double.toString(balance));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        HomePageUI ui = new HomePageUI();
        ui.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        jPanel2.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        jPanel2.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageWatchSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageWatchSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageWatchSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageWatchSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageWatchSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnprintbill;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rdoAnalog;
    private javax.swing.JRadioButton rdoCards;
    private javax.swing.JRadioButton rdoCash;
    private javax.swing.JRadioButton rdoDigital;
    private javax.swing.JRadioButton rdoSmart;
    private javax.swing.JTable tbl_maintable;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCusNIC;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPaidAmount;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSNum;
    private javax.swing.JTextField txt_cusname;
    private javax.swing.JTextArea txtbillFill;
    // End of variables declaration//GEN-END:variables
    private String WatchType;
    private String PaymentMethod;
    private double PaidAmount = 0.0;
    private double Price = 0.0;
    private double balance = 0.0;
}
