package Views;

import DBLayer.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class PayRepair extends javax.swing.JFrame {

    Color mouseEnterColor = new Color(255, 0, 0);
    Color mouseExitColor = new Color(204, 0, 0);

    int repair_id;
    double totalCost, amountPaid, amountDue, pay;
    DefaultTableModel model;

    public PayRepair() {
        initComponents();
    }

    //fetch payment details from repair table to the ui
    public void getPaymentDetails() {

        repair_id = Integer.parseInt(txt_repairid.getText());

        try {
            Connection con = DBConnection.getConnection();
            String sql = "select price, amount_paid, amount_due from repair where repair_id = ?;";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setInt(1, repair_id);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                txt_totalCost.setText(rs.getString("price"));
                txt_amountpaid.setText(rs.getString("amount_paid"));
                txt_amountDue.setText(rs.getString("amount_due"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    //update new payment details to the table
    public boolean updateRepairPayment() {
        boolean update = false;
        repair_id = Integer.parseInt(txt_repairid.getText());
        totalCost = Double.parseDouble(txt_totalCost.getText());
        amountPaid = Double.parseDouble(txt_amountpaid.getText());
        amountDue = Double.parseDouble(txt_amountDue.getText());
        pay = Double.parseDouble(txt_pay.getText());

        try {
            Connection con = DBConnection.getConnection();
            String sql = "update repair set price = ?, amount_paid = ?, amount_due = ? where repair_id = ?;";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setDouble(1, totalCost);
            pst.setDouble(2, amountPaid);
            pst.setDouble(3, amountDue);
            pst.setInt(4, repair_id);

            int rowCount = pst.executeUpdate();
            if (rowCount > 0) {
                update = true;
            } else {
                update = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return update;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_repairid = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_pay = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_amountDue = new javax.swing.JLabel();
        txt_totalCost = new javax.swing.JLabel();
        txt_amountpaid = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel1.setBackground(new java.awt.Color(0, 153, 153));
        JPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\icons8_Rewind_48px.png")); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        JPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Repair ID:");
        JPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 130, 30));
        JPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, -1));

        txt_repairid.setBackground(new java.awt.Color(0, 153, 153));
        txt_repairid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_repairid.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        txt_repairid.setPlaceholder("Enter Repair ID..");
        txt_repairid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_repairidFocusLost(evt);
            }
        });
        JPanel1.add(txt_repairid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 260, 40));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pay:");
        JPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, 30));
        JPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, -1));

        txt_pay.setBackground(new java.awt.Color(0, 153, 153));
        txt_pay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_pay.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        txt_pay.setPlaceholder("Enter Pay..");
        JPanel1.add(txt_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 260, 40));

        rSMaterialButtonCircle1.setText("PAY");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        JPanel1.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 220, 70));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 340, 5));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\blackdollar.png")); // NOI18N
        jLabel3.setText("Pay For Repair Job");
        JPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 510, 90));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Amount Due:");
        JPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 130, 30));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Amount Paid:");
        JPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 130, 30));

        jLabel19.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total Cost:");
        JPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 130, 30));

        txt_amountDue.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        txt_amountDue.setBorder(null);
        JPanel1.add(txt_amountDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 120, 30));

        txt_totalCost.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        txt_totalCost.setBorder(null);
        JPanel1.add(txt_totalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 120, 30));

        txt_amountpaid.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        txt_amountpaid.setBorder(null);
        JPanel1.add(txt_amountpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 120, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\dollar.png")); // NOI18N
        JPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akash\\OneDrive\\Desktop\\TimeTicker\\TimeTicker\\src\\main\\java\\icons\\maintenance.png")); // NOI18N
        JPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, 50));

        getContentPane().add(JPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 440));

        setSize(new java.awt.Dimension(846, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        RepairUI ui = new RepairUI();
        ui.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jPanel2.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jPanel2.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel1MouseExited

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        if (updateRepairPayment() == true) {
            double cost = Double.parseDouble(txt_totalCost.getText());
            double pay = Double.parseDouble(txt_pay.getText());

            try {
                Connection con = DBConnection.getConnection();
                String sql1 = "insert into income(income, date) values(?,curdate());";
                PreparedStatement pst1 = con.prepareStatement(sql1);
                
                pst1.setDouble(1, pay);
                pst1.executeUpdate();
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            double amount = Double.parseDouble(txt_amountpaid.getText()) + pay;
            double due = cost - amount;

            txt_amountDue.setText(String.valueOf(due));
            txt_amountpaid.setText(String.valueOf(amount));
            JOptionPane.showMessageDialog(this, "Payment Details Updated Successfully!");
            updateRepairPayment();
        } else {
            JOptionPane.showMessageDialog(this, "Payment Details Updation Failed!");
        }
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void txt_repairidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_repairidFocusLost
        getPaymentDetails();
    }//GEN-LAST:event_txt_repairidFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayRepair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JLabel txt_amountDue;
    private javax.swing.JLabel txt_amountpaid;
    private app.bolivia.swing.JCTextField txt_pay;
    private app.bolivia.swing.JCTextField txt_repairid;
    private javax.swing.JLabel txt_totalCost;
    // End of variables declaration//GEN-END:variables
}
